### ISSUE TITLE
Find files and directories beginning with a dot

### ISSUE THREAD

**Issue by Maltragor** [facelessuser/wcmatch#110]
Hi,
I tried to use pathlib.glob to find all files and directories (recursively) beginning with a dot, but the result was not as I expected.

Is the behaviour of the following examples really correct?
Python 3, wcmatch: 6.0.1

(The output of (1) corresponds to my directory structure)

```python
from wcmatch import pathlib

p = pathlib.Path("./test")

print("expexted")
print("\n1) **/*   GLOBSTAR | DOTGLOB")
for x in p.glob("**/*", flags= pathlib.GLOBSTAR | pathlib.DOTGLOB):
    print(x)

print("\n2) */* ")
for x in p.glob("*/*", flags=0 ):
    print(x)

print("\n3) **/.*  GLOBSTAR | DOTGLOB | NODIR")
for x in p.glob("**/.*", flags= pathlib.GLOBSTAR | pathlib.DOTGLOB | pathlib.NODIR):
    print(x)

print("\nunexpected / strange")
print("\n4) */.* ")
for x in p.glob("*/.*", flags=0 ):
    print(x)

print("\n5) **/.*   GLOBSTAR | DOTGLOB")
for x in p.glob("**/.*", flags= pathlib.GLOBSTAR | pathlib.DOTGLOB):
    print(x)

print("\n6) **/.*   GLOBSTAR")
for x in p.glob("**/.*", flags= pathlib.GLOBSTAR):
    print(x)
```

**Output:**

```
expexted

1) **/*   GLOBSTAR | DOTGLOB
test/file
test/sub
test/sub/.dotdir
test/sub/.dotfile
test/sub/dir

2) */* 
test/sub/dir

3) **/.*  GLOBSTAR | DOTGLOB | NODIR
test/sub/.dotfile

unexpected / strange

4) */.* 
test/sub                 // <- ?
test/sub/..              // <- ?
test/sub/.dotdir
test/sub/.dotfile

5) **/.*   GLOBSTAR | DOTGLOB
test                    // <- ?
test/..                 // ...
test/sub
test/sub/..            
test/sub/.dotdir        
test/sub/.dotdir        // <- ? duplicate
test/sub/.dotdir/..    
test/sub/.dotfile
test/sub/dir
test/sub/dir/..         

6) **/.*   GLOBSTAR
test
test/..
test/sub
test/sub/..
test/sub/dir
test/sub/dir/..
                         // <- ? no .dotfile / .dotdir compared to (4)
```

How would be the pattern and the flags to get the result of
```
$ find ./test -name ".*"
./test/sub/.dotdir
./test/sub/.dotfile
```

**Comment by facelessuser** [comment]
This may help clarify:

```py
>>> glob.glob('*/.*')
['tests/.', 'tests/..', 'wcmatch/.', 'wcmatch/..', 'requirements/.', 'requirements/..', 'docs/.', 'docs/..']
```

```py
>>> pathlib.Path('tests/.')
PosixPath('tests')
```

```py
>>> list(pathlib.Path('.').glob('*/.*'))
[PosixPath('tests'), PosixPath('tests/..'), PosixPath('wcmatch'), PosixPath('wcmatch/..'), PosixPath('requirements'), PosixPath('requirements/..'), PosixPath('docs'), PosixPath('docs/..')]
```

**Comment by facelessuser** [comment]
If you find capturing `.` or `..` folders a problem, you can always exclude them:

```py
list(pathlib.Path('.').glob(['**/.*', '!**/.', '!**/..'], flags=pathlib.GLOBSTAR | pathlib.NEGATE))
```

So, from what I see, it is working as expected, though I can understand why there was some confusion. The way that Pathlib normalizes directories can make things surprising.

@gir-bot remove S: triage
@gir-bot add S: support

**Comment by Maltragor** [comment]
Hi,
thank you for your fast response.

OK, the issue with the "/.." ending can be resolved by using an exclude pattern.

But the main point is:
6) **/.*   GLOBSTAR
-> There is none of the ".dotfile" / ".dotdir" in the result at all. But a lot of Elements not starting with a dot.

And your example 
```python
list(p.glob(['**/.*', '!**/.', '!**/..'], flags=pathlib.GLOBSTAR | pathlib.NEGATE))
```
returns an empty list, while 
```python
list(p.glob(['*/.*', '!**/.', '!**/..'], flags=pathlib.GLOBSTAR | pathlib.NEGATE))
```
returns as expected the two dot-elements.
-> So the point is, the strange (?) behaviour when using recursive "**" search so it can't be seen as a recursive-search-switch as I expected.

And in 5) **/.*   GLOBSTAR | DOTGLOB 
for example "test/sub/.dotdir" is returned twice, while 
```python
list(p.glob(['**/.*', '!**/.', '!**/..'], flags=pathlib.GLOBSTAR | pathlib.NEGATE |  pathlib.DOTGLOB))
```
returns the expected result - the two dot-Elements. (As I fount out in this moment)
So it seams that for example one of the "test/sub/.dotdir" is internally not identical to the other one an gets filtered by the exclude expression.
(And that "*/.*" without  DOTGLOB finds files starting with dot, while "**/.*" only finds them with DOTGLOB)

So maybe always using  ['!**/.', '!**/..'] with pathlib.GLOBSTAR | pathlib.NEGATE | pathlib.DOTGLOB for any search could work (not tested it with other patterns). Or what are the disadvantages for this configuration? (If expecting the behaviour of "find")

**Comment by facelessuser** [comment]
> But a lot of Elements not starting with a dot.

I'm not sure what you mean by this, I've shown that Pathlib will take a path like `test/.` and normalize it to just `test`, so that is why you may get paths without a dot.

But with that said. I think there is an issue. Not with a recursion not being a recursion or anything like, but it seems to more about how when using recursive `**` that `.dotfiles` are not getting included in the search unless `DOTGLOB` is enabled.

**Comment by facelessuser** [comment]
I think I understand what is causing the issue now in the code. I have a pull request to fix the issue here: https://github.com/facelessuser/wcmatch/pull/111. 

Note, that it was mentioned that sometimes you may get duplicates:

```
test/sub/.dotdir        
test/sub/.dotdir        // <- ? duplicate
```

This is not actually the case. What you are really getting is:

```
test/sub/.dotdir/.        
test/sub/.dotdir        // <- ? not duplicate
```

But Pathlib normalizes `test/sub/.dotdir/.` to look like `test/sub/.dotdir`. This matches Bash's behavior, but is a little confusing in Pathlib, which is why I suggested filtering out `.` and `..`.

You can try out the bugfix branch and see if that gives you sane results. I need to write some tests for the bugfix case, but, once I do and ensure the output is sane, I'll try and get a bugfix release out.

**Comment by facelessuser** [comment]
@gir-bot remove T: support
@gir-bot add T: bug

**Comment by facelessuser** [comment]
Logic fix dealing with `**` and dotfiles is on master. So I believe bugs are now fixed (but not yet released).

The question is whether, when using pathlib, we should leave out `.` and `..` results or not. 

Pathlib is inconsistent in how it handles such special directories:

```py
>>> pathlib.Path('tests/..')
PosixPath('tests/..')
>>> pathlib.Path('tests/.')
PosixPath('tests')
```

There seems to be logic to recognize `.` and normalize it. But when presented with `..` it doesn't seem to care. We can also see that Pathlib's handling of `.` is generally problematic as I detail here: https://github.com/facelessuser/wcmatch/issues/92#issuecomment-581188723. It is important to note that these issues exist with the builtin pathlib:

```py
>>> import pathlib
>>> str(pathlib.Path('.'))
'.'
>>> pathlib.Path('.').match('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\pathlib.py", line 939, in match
    raise ValueError("empty pattern")
ValueError: empty pattern
```

I personally think this normalization is not a good approach.

@Maltragor In short, the master branch should behave sanely now, but it will seemingly return some duplicates when matching something like `**/.*` as it may match `.test` and `.test/.` and results will normalize to `.test` and `.test`. The normalization is is not a `wcmatch` thing, but a `pathlib` normalization thing. We do return `.` and `..`, which is unique to wcmatch and just like what Bash does, but we do not normalize the paths in this confusing manner. Additionally, if it matches `test/.` `pathlib` will normalize to `test` and look like it matched a non-dotfile, but in fact, it did match what it was supposed to.

So is it better to have pathlib implementation to throw out `.` and `..` results? I open to opinions. If you can confirm that `master` appears to work as described, and let me know what you think about `.` and `..` handling, I would appreciate it.

**Comment by facelessuser** [comment]
I've created an experimental branch (https://github.com/facelessuser/wcmatch/pull/112) that causes `pathlib` to only return `.` and `..` when they are specified as explicit, literal patterns. That means `..` will match `..`, but `.*` would not. The same would be true for `.`. This would mean you would never see `.` and `..` unless you explicitly specify them. This would match the current `pathlib` approach as far as `.` and `..` is concerned.

This is, of course, experimental as I haven't decided whether to go this route or not. I've also only done minimal testing on it. The idea is it would only come into play if `glob` or `rglob` was used via a `pathlib` object. Feel free to evaluate it and give feedback.

**Comment by facelessuser** [comment]
The identified bug has been fixed. The mentioned enhancement in branch #112 is a separate consideration. If you find that the bugfix on master is not sufficient for sane behavior, feel free to reopen this issue. For comments on the experimental enhancement, please comment in #112.

**Comment by facelessuser** [comment]
FYI, 6.0.2 has been released with the fix.

```py
>>> from wcmatch import pathlib
>>> p = pathlib.Path('.')
>>> list(p.glob(['**/.*', '!**/.', '!**/..'], flags=glob.G | glob.N))
[PosixPath('.codecov.yml'), PosixPath('.tox'), PosixPath('.coverage'), PosixPath('tests/.test'), PosixPath('.coveragerc'), PosixPath('.gitignore'), PosixPath('.github'), PosixPath('.pyspelling.yml'), PosixPath('.git')]
```

This should get you sane behavior regardless of what happens with #112.

**Comment by Maltragor** [comment]
> Pathlib is inconsistent in how it handles such special directories:
> ```python
> >>> pathlib.Path('tests/..')
> PosixPath('tests/..')
> >>> pathlib.Path('tests/.')
> PosixPath('tests')
> ```
> There seems to be logic to recognize . and normalize it. But when presented with .. it doesn't seem to care.


How should 'tests/..' be normalised? (At least without filesystem access)
```
Example: 
+-- dirX
     +-- fileA 
+-- dirY
     +-- fileB
     +--SymLinkDirX
+-- fileC
```
```
$ ls dirY/SymLinkDirX/..
dirX  dirY  fileC
```
So 'dirY/SymLinkDirX/.. ' is not equal to 'dirY'.
And resolving symlinks seems only to be done by Path.resolve() which then can eliminate '/..'

On the other hand 'tests/.' and 'tests' describe the same path and can be normalised.


> This is not actually the case. What you are really getting is:
> 
> ```
> test/sub/.dotdir/.        
> test/sub/.dotdir        // <- ? not duplicate
> ```
> 
> But Pathlib normalizes test/sub/.dotdir/. to look like test/sub/.dotdir

But 'test/sub/.dotdir/.' is the same as 'test/sub/.dotdir' that's why it can be normalised.
So still, why is the path found two times?

You asked
> So is it better to have pathlib implementation to throw out . and .. results?
But I don' know what is the reason to generate 'path/.' and 'path/..' entries during file search at all.

 > We do return . and .., which is unique to wcmatch and just like what Bash does
Now I understand what you want to tell me^^
`$ echo docs/.*`
Ohh... I never used this mechanism to search for files... and yesterday... yes, there was a `echo` example in your documentation and  I was surprised why `echo wcmatch/*.py` should return file names... and ignored it ;-)

`echo **/.*` returns a list of 'directory/.' and 'directory/..' entries .. I see.
And that is your expected behaviour... while I expected the glob function to behave like `find` ... because I started with a shell script using find and then decided to use python... and started to search for a more powerful version of pathlib.glob().
And on top the normalisation which made the confusion complete :-) 

But now it's to late... time to sleep.
Knowing this two different expectations on the behaviour, I will read your answer and questions again in the next days, test the branch and give you feedback.

> So is it better to have pathlib implementation to throw out . and .. results? 
Probably there is no "better".. 
For me, I see no benefits in the 'directory/.' and 'directory/..' result because they are no "real" results of the search... (in my opinion). But as mentioned I didn't use this way of file search and someone else maybe is happy to get this behaviour.

Whereby this mixture, including  'directory/.' and 'directory/..' but then normalise them, resulting in a list with duplicates and not matching entries probably is a little strange.

Wow... still so hard-working... thank you :-)
what time is it at your place? Here it is 3:40.

**Comment by facelessuser** [comment]
`**/.*` matches  `test/sub/.dotdir/.` because `DOTGLOB` is enabled and `**` matches `test/sub/.dotdir` and then `.*` matches `.`. But `**/.*` also matchex `test/sub/.dotdir` because `**` matches `test/sub` and `.*` matches `.dotdir`. So you can see that `**/.*` matches both `test/sub/.dotdir/.` and `test/sub/.dotdir`. Pathlib, not wcmatch normalizes the returned paths to both look like `test/sub/.dotdir` by stripping out the `.`.

This behavior is the same as bash:

```
bash-5.0$ echo **/.*
. .. .test .test/. .test/..
```

So, pathlib just normalizes `.test` and `.test/.` to be `.test` by stripping out the `.` as `.test` and `.test/.` are basically equivalent.

**Comment by facelessuser** [comment]
As far as usefulness of `.` and `..`, `..` can actually be useful if you want to target a file relative to some other file. `.`, I admit, is less useful. We are matching Bash's behavior, so for completeness, we support it as well.

> what time is it at your place? Here it is 3:40.

MST (Mountain Standard Time) in the US.

**Comment by Maltragor** [comment]
As comment to your penultimate post:
At the end of last night I understood the technical reason.
On the one hand I have kept my question 
> But I don' know what is the reason to generate 'path/.' and 'path/..' entries during file search at all.

to show my train of thought. On the other hand it becomes to a non technical / implementation based question:
What is the reason / the idea why `echo **/.*` has `.test/. .test/..` in the, lets call it base set of elements it searches on.
(Of course, if it is in this base set, it will match...)

Based on my idea / the picture of the directory tree, there are only "real" directories. And searching on this set won't see a `.test/..` because it is the parent of `.test`. But the parent is already represented by its name (or by '.' as root) in this tree. And `.test/.` is the directory itself.
That `.test/. .test/..` notation on its own make sense is self-evident. Of course you need `/..` to express a parent relation.
But I have no Idea why a file search should have something like `.test/. .test/..` in its search base. 
Probably users of the bash glob functionality will laugh at me how I can ask such a stupid question.. But as I said in my initial idea the search was working on the tree of the "really" existing elements you can see in the file manager / get presented by ls.
And that naturally led to a different expectation.

So at this point the discussion is not about having `/..` and `/.` or not at all.
And it's not about the the way your glob function does work correctly. You're the one who's pretending how it should behave. And I'm sure there is a reason why you prefer the bash way. (And I understand that your pathlib.glob() is only a part of your library so the starting point of the consideration should not be the behaviour of pathlib.glob())
For me it is the recognition that there at least exist this two ways and that there is a possibility to get my preferred/expected way.
And being aware of the need to filter some results or maybe having a switch-falg should make every one happy.

So the only thing to discuss further could be the mixture of bash glob behaviour in combination with pathlib when using your pathlib.glob(). -> #112.

**Comment by Maltragor** [comment]
> `pathlib.Path('.').match('.')`

just a thought because you mentioned it.

- '.' is the current directory / is the respectively mentioned directory
- so "abc/." is "abc" and "abc" is "abc/." with exception that pathlib normalisation changes the path only the one way by removing the '/.'

But based on this:
If allowing .match('.'), should  `pathlib.Path('abc/.').match('.')` be True or False?
Technically 'abc/.' is normalised to 'abc' and of course 'abc' does not match '.'
But as I understand the idea behind match is to compare from right to left (*1). And the last segment of 'abc/. is a dot, so it would match. And because 'abc' is 'abc/.',  thinking of an inverse normalisation, every path would match.
And thinking of '.' as current (mentioned) directory... every directory I use as base is the current directory.

Thinking about this I was asking me, if the assertion of match('.') is the effect of an unhandled normalisation issue, or if it should express that this kind of match comparison is something special the user shouldn't do or handle in an individual way.

(*1) But because I was looking for something that supports Path('abc/def/xyz.txt').match('abc/**') at the end I found your library, providing globmatch() and even better allowing exclude patterns so there is no need to filter directories in an post processing step.

**Comment by facelessuser** [comment]
> But as I understand the idea behind match is to compare from right to left (*1). And the last segment of 'abc/. is a dot, so it would match. And because 'abc' is 'abc/.', thinking of an inverse normalization, every path would match.
And thinking of '.' as current (mentioned) directory... every directory I use as base is the current directory.

It doesn't actually match from right to left per se, but kind of does a recursive match, so something like `**/.` is what it is actually doing, so in a way I guess you are kind of right. I guess I'm not sure how the standard `pathlib` does this exactly. I know they use a different algorithm than the standard `glob` library to do their matching and such even though they are replicating the same behavior (kind of).

The reason why this fails in the standard `pathlib` is that they normalize the file, which prevents `.` from matching it in the first place, and then they normalize the pattern from `"."` to `""` which causes a pattern error. My biggest problem is that they alter the explicit pattern a user gives and changes its meaning.

> If allowing .match('.'), should pathlib.Path('abc/.').match('.') be True or False?

In my opinion, I don't think `pathlib.Path('abc/.').match('.')` should match. I look at `.` as a pattern, no different from using regex to match something. It is a pattern syntax that has rules, so I don't think it should interpret much what we think it *should* mean, but instead take it pretty much at face value.

I guess this is up to interpretation though. The way I approached `wcmatch.globmatch`, (which I use for our `pathlib` implementation) is that `globmatch` matches what `glob` globs. What I mean by that is when you give `glob` a pattern, based on that pattern, it will return certain paths. So the pattern that you give `globmatch` should match paths that `glob` would return.

So, if I glob `abc/.`, it will return `abc/.`. It does not return `abc`; therefore, if I use `globmatch` and the pattern `abc/.`, it will only match `abc/.` and **not** `abc`. There isn't a lot of "magic" going on per se. The only magic we allow is slash normalization:

1. `/` will match `\` on windows. This eases a lot of frustration.

2. We are forgiving of things like `my//path///to//a/file` so that matching with the pattern `/` will still match `//` and `///` etc. as shells will treat multiple `/` as one as well.

    ```
    ➜  wcmatch git:(master) cd docs////src
    ➜  src git:(master)
    ```

    Double slashes have no significant meaning except in Windows drives and UNC paths, and those are already handled special, so double slashes anywhere else we can just ignore. This is probably the most "magical" thing that I think we do.

3. We also have no problem matching trailing slashes that are not explicitly specified in the pattern, as `glob` will match both directories and files if given the pattern `tests`, but if you give it the pattern `tests/` it will only match directories. So in that case of `globmatch`, if you give the pattern `test/` it will only match the path if it ends in `/` which signifies it is a directory, but if you give it `test` it will match `test` or `test/`. This isn't too different from what other glob matching libraries I've seen around, so we are in good company.

---

Too much magic confuses users, which is why Pathlib's normalizations frustrate me a bit. If I give it `.`, I kind of expect that to be my path, but even if it normalizes it, I would expect the pattern `.` to not be altered in a significant way which changes its meaning. In this case, I think that is what `pathlib` does. `pathlib` does the same normalization that it does to paths to the patterns, so when I give it the pattern `.` it turns it into an empty string causing the match function to throw an error. This is confusing and unexpected.

I also don't like that `pathlib` strips off trailing `/`. If you are using a `PurePath`, which will not access the filesystem, it is impossible to tell if the path was supposed to be a directory or a file. You can not filter PurePaths to match only folders or only files. I guess their argument is that `pathlib` just handles path is an abstract way. A trailing `/` doesn't actually have significance, and they don't feel there is a path syntax that exists to give context as to whether a path is a file or a directory. It's a fair argument. I think the trailing slash is maybe something we as people assume, but it is a useful assumption 🤷.

---

Anyways, `match` has its uses, and I don't have a specific issue with `match`, it is more the `.` normalization and trailing slash normalization of `pathlib`.

I think `match` has its uses, but I also feel `globmatch` has its uses as well. I like having both.

**Comment by Maltragor** [comment]
> But as I understand the idea behind match is to compare from right to left

This statement belongs to the **original version**, and this is why I mentioned in (*1), that I was not happy with this implementation.

Original pathlib.match()
https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.match
> If pattern is relative, the path can be either relative or absolute, and matching is done from the right

```python
Path('test/abc/def/xyz.txt').match('test/**/xyz.txt')
```

```python
def match(self, path_pattern):
        cf = self._flavour.casefold
        path_pattern = cf(path_pattern)
        drv, root, pat_parts = self._flavour.parse_parts((path_pattern,))
        if not pat_parts:
            raise ValueError("empty pattern")
        if drv and drv != cf(self._drv):
            return False
        if root and root != cf(self._root):
            return False
        parts = self._cparts
        if drv or root:
            if len(pat_parts) != len(parts):
                return False
            pat_parts = pat_parts[1:]
        elif len(pat_parts) > len(parts):
            return False
        for part, pat in zip(reversed(parts), reversed(pat_parts)):
            if not fnmatch.fnmatchcase(part, pat):
                return False
        return True
```

=> Split path-path and match-path in segments: parts and pat_parts:  ['test', 'abc', 'def', 'xyz.txt'] and ['test', '**', 'xyz.txt']
=> In reverse order, compare the elements with fnmatchcase: [('xyz.txt', 'xyz.txt'), ('def', '**'), ('abc', 'test')]
=> '**' only matches one path element ..
=> No Match

**Comment by facelessuser** [comment]
Okay, so I guess we sort of emulate that behavior in our `match`. I've always found `globmatch` more useful, so that is usually what I use 🙂.

**Comment by Maltragor** [comment]
And to get clear, the  `pathlib.Path('abc/.').match('.') ` comment was just a thought if there is anything special on match('.') other than the normalisation to "". 
So I asked **me** wether the author of the **original version** has given a great deal or little thought when decided to throw an exception.
Probably the exception is only the consequence of the normalisation. But because you modified the behaviour and mentioned it last time, I wanted to share my thoughts with you.
Not more, not less.
I have no real opinion on a correct match definition in this case. Of course the most obvious handling would be a standard regex match. But if someone likes, it would be possible to find arguments for an other handling and so it would be possible to argue that a exception is a expected behaviour in a case the author decided to give the decision to the user.

Probably I thought to much about it.. I know ;-)

**Comment by Maltragor** [comment]
> globmatch more useful

I completely agree with you.
After I recognized that the original match does "strange things" in comparison with the glob behaviour I only thought.. shit... really? No way to compare to paths in a "normal" way / similar to the glob search?! I do not want to deal with having to implement the comparison myself.. I only want to find files using an exclude expression... I decided to use python in the expectation this will be easier than using bash with find and loops...

**Comment by facelessuser** [comment]
This discussion at least did bring up the fact that while we want to emulate `match`, I don't think we are doing it quite right. Since they match right to left, we should provide that feel of right to left matching in `match` as well. We wanted to provide the function with the same feel (because I'm sure someone as a reason to prefer this function), but with the added benefits and options of our library. So I need to fix this to at least mimic this behavior. Instead of prepending a glob pattern of `**`, we need to append the regex pattern of `.*?`. That will properly emulate the feel. I guess I never dug in deep enough to fully understand what they were doing as I honestly never intended to use `match` 🙂.

`globmatch` will keep operating as it always has, which I prefer. Based on the realization that it isn't recursive in the sense I thought, I think `match` should probably use a simple `.*?` regex match prepended. That will ensure it "feels" like we are matching right to left as we will allow anything to come before it.
