### ISSUE TITLE
Bring wcmatch to ST3

### ISSUE THREAD

**Issue by rwols** [facelessuser/wcmatch#131]
I would like to use the recursive globstar (`**`) and brace-expansion capabilities of this library in LSP, but it is not available as a sublime dependency for ST3. I was hesitant to request this because it could be a lot of work. But seeing as you've already got it working I might as well go ahead and request it.

Related: https://github.com/sublimelsp/LSP/issues/1216

**Comment by facelessuser** [comment]
No worries. I only looked into it because I had done so previously. I thought about using it in ApplySyntax, but then I thought I'd wait till ST4 supported dependencies. I'm a little more motivated when it is someone beyond myself that also desires it.

The one thing you won't get is the ability to use `wcmatch`'s `pathlib` derivative (for obvious reasons), but that should be fine.

The necessary dependencies are already on ST:

- backrefs which we tap into to get property classes: `[[:alnum:]]`.
- bracex which we use for Bash style brace expansion.

If possible, I will try and set up a python 3.3 environment (outside ST) just to run a sanity check of tests. I'd like to make sure there is nothing hidden that would break in some case beyond my basic evaluation.

**Comment by facelessuser** [comment]
@rwols The Sublime Text dependency has been created: https://github.com/facelessuser/sublime-wcmatch.

Everything seems to work, I ran the whole test suite on it. Apparently Sublime has a pathlib dependency, so if that is loaded, you can even use wcmatch's derived pathlib.

If you can see getting it on Package Control, that'd be great. You can test it before if you have your own package control repository file and add this to dependencies:

```js
        {
            "name": "wcmatch",
            "author": "facelessuser",
            "load_order": "51",
            "description": "wcmatch",
            "issues": "https://github.com/facelessuser/sublime-wcmatch/issues",
            "releases": [
                {
                    "base": "https://github.com/facelessuser/sublime-wcmatch",
                    "tags": true,
                    "sublime_text": ">=3000"
                }
            ]
        }
```

**Comment by facelessuser** [comment]
I went a head and got it started: https://github.com/wbond/package_control_channel/pull/7999.

**Comment by facelessuser** [comment]
Closing this issue as we are just waiting for Package Control to merge it.

If you run into Sublime specific issues, feel free to create an issue over at https://github.com/facelessuser/sublime-wcmatch.

Non, Sublime specific issues would go here, of course.

**Comment by rwols** [comment]
Thanks for being so swift :) I just got back from work and it's already a pull request

**Comment by facelessuser** [comment]
No worries. FichteFoll mentioned he needed to do some reviews before vacation, so I decided to just push it up in the hopes that he'll get to it before vacation. We'll see 🤷 .

**Comment by facelessuser** [comment]
It's on PC now.
