### ISSUE TITLE
document similar libraries from other laguages

### ISSUE THREAD

**Issue by ssbarnea** [facelessuser/wcmatch#170]
I think it would be very useful to document if there are kinda similar libraries on other languages. I am in particular interested about JavaScript/TypeScript as I found a real case where I need to re-use the same patterns on both Python and JavaScript.

They do not need to be ports, but if the basics are the same it would be nice to document them.

**Comment by facelessuser** [comment]
I think this might be a bit much to ask. I don't have time to research in various other languages what libraries are similar to this one. I would also argue that any library offering file globbing is similar to this 🙂 .

## Similarities

Base globbing I imagine is similar across most globs. In addition, I think I've seen similar features for `MARK`, `NOUNIQUE`, `NODIR`, `MATCHBASE`, `BRACE`, `EXTGLOB`, `FOLLOW`, and `GLOBSTAR`. You can check https://github.com/isaacs/node-glob which I think implements most of these. There may be others, but I can't evaluate all options out there.

I don't know if all libraries have backslash escapes enabled by default. I don't think this is unique per se, but maybe not all implement it? Some may even have this configurable (ours is just the default behavior).

Using POSIX style character classes is not always common, but some have it and some don't. Ours is definitely not locale-aware, and currently just uses the C locale. If we changed anything with this in the future, we'd just add the Unicode equivalent compatible with the POSIX intent.

I'm not sure if `CASE` and `IGNORECASE` are common or not, but I don't think the feature is unique.

## Maybe Unique, but Not Relevant to Discussion?

- `SCANDOTDIR` just controls whether `glob` file scanning returns `.` and `..` in results. By default, you have to use an explicit `.` and `..` to match these "special" folders. This is more ZSH style behavior and models what Python's default glob does because that is how the underlying `scandir` in Python works. By enabling `SCANDOTDIR`, we inject `.` and `..` into the returned paths giving you a Bash style behavior where `.*` will match both `.` and `..`. This is just related to how the file crawling works, the patterns still technically match `.` and `..` unless you use `NODOTDIR`. To be honest, unless you are specifically trying to match Bash, this isn't useful to enable.
- `NODOTDIR` ensures that the patterns themselves exhibit this ZSH style behavior, so things like `globmatch` will not match `.` and `..` unless `.` and `..` are explicitly used in the pattern. Most glob libraries probably exhibit the Bash style matching in their path matching logic.

## Differences

As far as differences, I can make a general statement. Most of the differences are related to OS-aware context or special features I needed for [Rummage](https://github.com/facelessuser/Rummage).

- UNC paths on Windows probably aren't considered by a lot of libraries. Python's default glob does, so we do as well.
- Other libraries may not count `r'\\'` as a path separator on Windows. This is convenient for people with "Windows brain", but not something that most people will run into.
- I imagine other libraries don't also ensure that `/` matches both `/` and `\` on windows without normalizing Window's paths to using `/` only. The regex patterns we generate with `translate` on a Windows machine (or when using `FORCEWIN`) should match Windows paths with `\` or `/` so people can just use them. This makes it easy for people with "Windows brain" on a Windows machine so they don't have to keep normalizing all their paths. But they can do that too if they want.
- I'm pretty sure `FORCEWIN` and `FORCEUNIX` are unique to us. That just forces Windows logic (UNC paths, Windows path separators, etc.) vs Unix logic. By default, wcmatch just uses the logic for the system it is on.
- These were added specifically as I had a use for them in my GUI application [Rummage](https://github.com/facelessuser/Rummage).
	- `SPLIT` flag was required for the GUI interface that allowed you to specify multiple glob patterns in one input separated by `|`. I needed a glob pattern-aware splitter that could target `|`.
	- `NEGATE` adds pattern exclusion for patterns that start with `!`. I think there was one library that used to do this but then changed it to just accept an exclude parameter with a list of normal patterns. This was useful for our interface in Rummage and why it was initially added.
	- `MINUSNEGATE`: This stemmed from a conflict in using the pattern exclusion feature of `!` (with the `NEGATE` flag) at the start of a file and the `EXTMATCH`/`EXTGLOB` feature (which uses patterns such as `!(...)`) together. Later, I've resolved this by simply adding logic that if `!` is followed by `(` when the two are enabled together, `!` will not be treated as a `NEGATE` pattern unless you escape `(`. `MINUSNEGATE` is not really needed anymore and is mainly kept around as that was Rummage's default for a long time.
	- `RAWCHARS` is a feature that was added specifically to allow passing in the same notation for that Python uses for Unicode and such in a GUI. Things like `\u1045` and such are not part of the GLOB spec but can be useful sometimes for a user through a GUI. I sort of just added it so I could take advantage of it in Rummage or other similar interfaces. I honestly may be the only one using that feature, but 🤷 .
- `GLOBTILDE` may or may not be unique.

Anyways, that is the best I can offer.

@gir-bot remove S: triage
@gir-bot add S: support

**Comment by facelessuser** [comment]
> Thanks for the detailed explanation. I was also able to get some extra fedback related to what is available on JS/TS world on [redhat-developer/yaml-language-server#422 (comment)](https://github.com/redhat-developer/yaml-language-server/issues/422#issuecomment-792787565) - Maybe it would woth mentioning wcmatach on wikipedia page [en.wikipedia.org/wiki/Glob_(programming)#cite_note-py-17](https://en.wikipedia.org/wiki/Glob_(programming)#cite_note-py-17)

I'm not averse to it 🤷.

**Comment by facelessuser** [comment]
As the question has been answered, and there is no action item (I don't intend to keep an exhaustive comparison between other libs), I will go ahead and close this.
